---
transmission_enabled: false
transmission_available_externally: false

# Default values for instances
transmission_defaults:
  name_prefix: "transmission"
  config_directory_base: "{{ docker_home }}/transmission/config"
  download_directory_base: "{{ downloads_root }}"
  watch_directory_base: "{{ torrents_root }}"
  user_id: "0"
  group_id: "0"
  webui_port_start: "9092"
  external_port_start: "51414"
  hostname_prefix: "transmission"
  timezone: "{{ ansible_nas_timezone }}"
  image_name: "linuxserver/transmission"
  image_version: "latest"
  memory: "1g"

# List of transmission instances (will be populated by user config)
transmission_instances: []
